// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: computers_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetComputersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetComputersRequest) Reset() {
	*x = GetComputersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_computers_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetComputersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComputersRequest) ProtoMessage() {}

func (x *GetComputersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_computers_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComputersRequest.ProtoReflect.Descriptor instead.
func (*GetComputersRequest) Descriptor() ([]byte, []int) {
	return file_computers_service_proto_rawDescGZIP(), []int{0}
}

type ComputerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Computer `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ComputerList) Reset() {
	*x = ComputerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_computers_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComputerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerList) ProtoMessage() {}

func (x *ComputerList) ProtoReflect() protoreflect.Message {
	mi := &file_computers_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerList.ProtoReflect.Descriptor instead.
func (*ComputerList) Descriptor() ([]byte, []int) {
	return file_computers_service_proto_rawDescGZIP(), []int{1}
}

func (x *ComputerList) GetList() []*Computer {
	if x != nil {
		return x.List
	}
	return nil
}

type Computer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Model  string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Cpu    string `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory string `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Price  int64  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Computer) Reset() {
	*x = Computer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_computers_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Computer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Computer) ProtoMessage() {}

func (x *Computer) ProtoReflect() protoreflect.Message {
	mi := &file_computers_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Computer.ProtoReflect.Descriptor instead.
func (*Computer) Descriptor() ([]byte, []int) {
	return file_computers_service_proto_rawDescGZIP(), []int{2}
}

func (x *Computer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Computer) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Computer) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *Computer) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *Computer) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ComputerId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ComputerId) Reset() {
	*x = ComputerId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_computers_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComputerId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerId) ProtoMessage() {}

func (x *ComputerId) ProtoReflect() protoreflect.Message {
	mi := &file_computers_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerId.ProtoReflect.Descriptor instead.
func (*ComputerId) Descriptor() ([]byte, []int) {
	return file_computers_service_proto_rawDescGZIP(), []int{3}
}

func (x *ComputerId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_computers_service_proto protoreflect.FileDescriptor

var file_computers_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22,
	0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x75, 0x74, 0x65, 0x72, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x70, 0x0a, 0x08, 0x43, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03,
	0x63, 0x70, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x1c, 0x0a, 0x0a,
	0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0xa4, 0x02, 0x0a, 0x10, 0x43,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x31, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x12, 0x10,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x1a, 0x0e, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72,
	0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65,
	0x72, 0x73, 0x12, 0x19, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d,
	0x70, 0x75, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x70, 0x75, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x6f, 0x6d,
	0x70, 0x75, 0x74, 0x65, 0x72, 0x1a, 0x0e, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x6f, 0x6d,
	0x70, 0x75, 0x74, 0x65, 0x72, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x0e, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x22, 0x00, 0x12, 0x32, 0x0a,
	0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x12,
	0x0e, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x1a,
	0x0e, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x22,
	0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_computers_service_proto_rawDescOnce sync.Once
	file_computers_service_proto_rawDescData = file_computers_service_proto_rawDesc
)

func file_computers_service_proto_rawDescGZIP() []byte {
	file_computers_service_proto_rawDescOnce.Do(func() {
		file_computers_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_computers_service_proto_rawDescData)
	})
	return file_computers_service_proto_rawDescData
}

var file_computers_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_computers_service_proto_goTypes = []interface{}{
	(*GetComputersRequest)(nil), // 0: auth.GetComputersRequest
	(*ComputerList)(nil),        // 1: auth.ComputerList
	(*Computer)(nil),            // 2: auth.Computer
	(*ComputerId)(nil),          // 3: auth.ComputerId
}
var file_computers_service_proto_depIdxs = []int32{
	2, // 0: auth.ComputerList.list:type_name -> auth.Computer
	3, // 1: auth.ComputersService.GetComputer:input_type -> auth.ComputerId
	0, // 2: auth.ComputersService.GetComputers:input_type -> auth.GetComputersRequest
	2, // 3: auth.ComputersService.CreateComputer:input_type -> auth.Computer
	3, // 4: auth.ComputersService.DeleteComputer:input_type -> auth.ComputerId
	2, // 5: auth.ComputersService.UpdateComputer:input_type -> auth.Computer
	2, // 6: auth.ComputersService.GetComputer:output_type -> auth.Computer
	1, // 7: auth.ComputersService.GetComputers:output_type -> auth.ComputerList
	2, // 8: auth.ComputersService.CreateComputer:output_type -> auth.Computer
	2, // 9: auth.ComputersService.DeleteComputer:output_type -> auth.Computer
	2, // 10: auth.ComputersService.UpdateComputer:output_type -> auth.Computer
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_computers_service_proto_init() }
func file_computers_service_proto_init() {
	if File_computers_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_computers_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetComputersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_computers_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComputerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_computers_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Computer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_computers_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComputerId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_computers_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_computers_service_proto_goTypes,
		DependencyIndexes: file_computers_service_proto_depIdxs,
		MessageInfos:      file_computers_service_proto_msgTypes,
	}.Build()
	File_computers_service_proto = out.File
	file_computers_service_proto_rawDesc = nil
	file_computers_service_proto_goTypes = nil
	file_computers_service_proto_depIdxs = nil
}
