// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: phones_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPhonesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPhonesRequest) Reset() {
	*x = GetPhonesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phones_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPhonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhonesRequest) ProtoMessage() {}

func (x *GetPhonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phones_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhonesRequest.ProtoReflect.Descriptor instead.
func (*GetPhonesRequest) Descriptor() ([]byte, []int) {
	return file_phones_service_proto_rawDescGZIP(), []int{0}
}

type PhoneList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Phone `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *PhoneList) Reset() {
	*x = PhoneList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phones_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhoneList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneList) ProtoMessage() {}

func (x *PhoneList) ProtoReflect() protoreflect.Message {
	mi := &file_phones_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneList.ProtoReflect.Descriptor instead.
func (*PhoneList) Descriptor() ([]byte, []int) {
	return file_phones_service_proto_rawDescGZIP(), []int{1}
}

func (x *PhoneList) GetList() []*Phone {
	if x != nil {
		return x.List
	}
	return nil
}

type Phone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Brand string `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Year  int64  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Price int64  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Phone) Reset() {
	*x = Phone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phones_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Phone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phone) ProtoMessage() {}

func (x *Phone) ProtoReflect() protoreflect.Message {
	mi := &file_phones_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phone.ProtoReflect.Descriptor instead.
func (*Phone) Descriptor() ([]byte, []int) {
	return file_phones_service_proto_rawDescGZIP(), []int{2}
}

func (x *Phone) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Phone) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Phone) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Phone) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Phone) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type PhoneId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PhoneId) Reset() {
	*x = PhoneId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phones_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhoneId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneId) ProtoMessage() {}

func (x *PhoneId) ProtoReflect() protoreflect.Message {
	mi := &file_phones_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneId.ProtoReflect.Descriptor instead.
func (*PhoneId) Descriptor() ([]byte, []int) {
	return file_phones_service_proto_rawDescGZIP(), []int{3}
}

func (x *PhoneId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_phones_service_proto protoreflect.FileDescriptor

var file_phones_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0x12, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x2c, 0x0a, 0x09, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x6d,
	0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72,
	0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x19, 0x0a,
	0x07, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0xf4, 0x01, 0x0a, 0x0d, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x0d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x49, 0x64, 0x1a, 0x0b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x73, 0x12, 0x16, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x0b,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x0b, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x1a, 0x0b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x0d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x49, 0x64, 0x1a, 0x0b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x12, 0x0b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x1a, 0x0b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x42,
	0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_phones_service_proto_rawDescOnce sync.Once
	file_phones_service_proto_rawDescData = file_phones_service_proto_rawDesc
)

func file_phones_service_proto_rawDescGZIP() []byte {
	file_phones_service_proto_rawDescOnce.Do(func() {
		file_phones_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_phones_service_proto_rawDescData)
	})
	return file_phones_service_proto_rawDescData
}

var file_phones_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_phones_service_proto_goTypes = []interface{}{
	(*GetPhonesRequest)(nil), // 0: auth.GetPhonesRequest
	(*PhoneList)(nil),        // 1: auth.PhoneList
	(*Phone)(nil),            // 2: auth.Phone
	(*PhoneId)(nil),          // 3: auth.PhoneId
}
var file_phones_service_proto_depIdxs = []int32{
	2, // 0: auth.PhoneList.list:type_name -> auth.Phone
	3, // 1: auth.PhonesService.GetPhone:input_type -> auth.PhoneId
	0, // 2: auth.PhonesService.GetPhones:input_type -> auth.GetPhonesRequest
	2, // 3: auth.PhonesService.CreatePhone:input_type -> auth.Phone
	3, // 4: auth.PhonesService.DeletePhone:input_type -> auth.PhoneId
	2, // 5: auth.PhonesService.UpdatePhone:input_type -> auth.Phone
	2, // 6: auth.PhonesService.GetPhone:output_type -> auth.Phone
	1, // 7: auth.PhonesService.GetPhones:output_type -> auth.PhoneList
	2, // 8: auth.PhonesService.CreatePhone:output_type -> auth.Phone
	2, // 9: auth.PhonesService.DeletePhone:output_type -> auth.Phone
	2, // 10: auth.PhonesService.UpdatePhone:output_type -> auth.Phone
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_phones_service_proto_init() }
func file_phones_service_proto_init() {
	if File_phones_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_phones_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPhonesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phones_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhoneList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phones_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Phone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phones_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhoneId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_phones_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_phones_service_proto_goTypes,
		DependencyIndexes: file_phones_service_proto_depIdxs,
		MessageInfos:      file_phones_service_proto_msgTypes,
	}.Build()
	File_phones_service_proto = out.File
	file_phones_service_proto_rawDesc = nil
	file_phones_service_proto_goTypes = nil
	file_phones_service_proto_depIdxs = nil
}
